[ui.window.box]
width = 460
min_width = 380
max_width = 520
height = 320
min_height = 220
max_height = 380

[ui.window.box.scroll.list]
height = 220
min_height = 140
max_height = 280
width = 420
min_width = 340
max_width = 480

[ui.window.box.scroll.list.item.icon]
pixel_size = 24

[ui.window.box.scroll.list.item]
h_align = "start"
min_width = 320
width = 390
max_width = 450
